# Generated by Django 6.0.3 on 2026-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firm_address_user_firm_name_user_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='firm_logos/'),
        ),
    ]
