# Generated by Django 6.0.3 on 2026-07-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('member_type', models.CharField(choices=[('floor_joist', 'Floor joist'), ('ceiling_joist_no_storage', 'Ceiling joist (no attic storage)'), ('ceiling_joist_limited_storage', 'Ceiling joist (limited attic storage)'), ('rafter_no_ceiling', 'Rafter (no ceiling finish attached)'), ('rafter_with_ceiling', 'Rafter (with ceiling finish attached)'), ('beam_header', 'Beam / header')], max_length=40)),
                ('span_ft', models.FloatField()),
                ('dead_load_plf', models.FloatField(default=0)),
                ('live_load_plf', models.FloatField(default=0)),
                ('nominal_size', models.CharField(choices=[('2x4', '2x4'), ('2x6', '2x6'), ('2x8', '2x8'), ('2x10', '2x10'), ('2x12', '2x12')], max_length=10)),
                ('repetitive', models.BooleanField(default=False)),
                ('bearing_length_in', models.FloatField(default=1.5)),
                ('point_loads', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beam_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
