# Generated by Django 6.0.3 on 2026-07-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='support_type_left',
            field=models.CharField(choices=[('wall_plate', 'Wall / Plate'), ('column', 'Column / Post'), ('hanger', 'Hanger')], default='wall_plate', max_length=20),
        ),
        migrations.AddField(
            model_name='beamdesign',
            name='support_type_right',
            field=models.CharField(choices=[('wall_plate', 'Wall / Plate'), ('column', 'Column / Post'), ('hanger', 'Hanger')], default='wall_plate', max_length=20),
        ),
    ]
