# Generated by Django 6.0.3 on 2026-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0002_beamdesign_support_type_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='snow_load_plf',
            field=models.FloatField(default=0),
        ),
    ]
