# Generated by Django 6.0.3 on 2026-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0003_beamdesign_snow_load_plf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamdesign',
            name='bearing_length_in',
        ),
        migrations.AddField(
            model_name='beamdesign',
            name='bearing_length_left_in',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='beamdesign',
            name='bearing_length_right_in',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='beamdesign',
            name='span_mode',
            field=models.CharField(choices=[('out_to_out', 'Out to out (outside face of bearing to outside face of bearing)'), ('inside', 'Inside span (inside face of bearing to inside face of bearing)'), ('center_to_center', 'Center to center of bearing')], default='inside', max_length=20),
        ),
    ]
