# Generated by Django 6.0.3 on 2026-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0004_remove_beamdesign_bearing_length_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='left_overhang_ft',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beamdesign',
            name='right_overhang_ft',
            field=models.FloatField(default=0),
        ),
    ]
