# Generated by Django 6.0.3 on 2026-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0010_beamdesign_extra_spans_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamdesign',
            name='support_type_mid_2',
            field=models.CharField(choices=[('wall_plate', 'Wall / Plate'), ('column', 'Column / Post'), ('hanger', 'Hanger')], default='wall_plate', max_length=20),
        ),
    ]
