# Generated by Django 6.0.3 on 2026-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0018_beamprojectissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='plies',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ply'), (2, '2 plies'), (3, '3 plies'), (4, '4 plies')], default=1),
        ),
    ]
