# Generated by Django 6.0.3 on 2026-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0019_beamdesign_plies'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='unbraced_length_ft',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
