# Generated by Django 6.0.3 on 2026-07-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0020_beamdesign_unbraced_length_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='service_condition',
            field=models.CharField(choices=[('dry', 'Dry (interior / protected)'), ('wet', 'Wet / exterior (MC > 19%)')], default='dry', max_length=10),
        ),
    ]
