# Generated by Django 6.0.3 on 2026-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0021_beamdesign_service_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamdesign',
            name='material',
            field=models.CharField(choices=[('spf_ss', 'Spruce-Pine-Fir Select Structural'), ('spf_no1', 'Spruce-Pine-Fir No. 1'), ('spf_no2', 'Spruce-Pine-Fir No. 2'), ('dfl_ss', 'Douglas Fir-Larch Select Structural'), ('dfl_no1', 'Douglas Fir-Larch No. 1'), ('dfl_no2', 'Douglas Fir-Larch No. 2'), ('hf_ss', 'Hem-Fir Select Structural'), ('hf_no1', 'Hem-Fir No. 1'), ('hf_no2', 'Hem-Fir No. 2'), ('lvl_1_9e', '1.9E LVL (representative)'), ('lvl_2_0e', '2.0E LVL (representative)')], default='spf_no2', max_length=20),
        ),
        migrations.AlterField(
            model_name='beamdesign',
            name='nominal_size',
            field=models.CharField(choices=[('2x4', '2x4'), ('2x6', '2x6'), ('2x8', '2x8'), ('2x10', '2x10'), ('2x12', '2x12'), ('lvl_7.25', '7-1/4"'), ('lvl_9.25', '9-1/4"'), ('lvl_11.25', '11-1/4"'), ('lvl_11.875', '11-7/8"'), ('lvl_14', '14"'), ('lvl_16', '16"'), ('lvl_18', '18"')], max_length=20),
        ),
    ]
