# Generated by Django 6.0.3 on 2026-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0022_alter_beamdesign_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamdesign',
            name='material',
            field=models.CharField(choices=[('spf_ss', 'Spruce-Pine-Fir Select Structural'), ('spf_no1', 'Spruce-Pine-Fir No. 1'), ('spf_no2', 'Spruce-Pine-Fir No. 2'), ('dfl_ss', 'Douglas Fir-Larch Select Structural'), ('dfl_no1', 'Douglas Fir-Larch No. 1'), ('dfl_no2', 'Douglas Fir-Larch No. 2'), ('hf_ss', 'Hem-Fir Select Structural'), ('hf_no1', 'Hem-Fir No. 1'), ('hf_no2', 'Hem-Fir No. 2'), ('lvl_1_55e', '1.55E LVL'), ('lvl_1_75e', '1.75E LVL'), ('lvl_1_9e', '1.9E LVL'), ('lvl_2_0e', '2.0E LVL'), ('lvl_2_1e', '2.1E LVL')], default='spf_no2', max_length=20),
        ),
    ]
