# Generated by Django 6.0.3 on 2026-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0023_alter_beamdesign_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamdesign',
            name='material',
            field=models.CharField(choices=[('spf_ss', 'Spruce-Pine-Fir Select Structural'), ('spf_no1', 'Spruce-Pine-Fir No. 1'), ('spf_no2', 'Spruce-Pine-Fir No. 2'), ('dfl_ss', 'Douglas Fir-Larch Select Structural'), ('dfl_no1', 'Douglas Fir-Larch No. 1'), ('dfl_no2', 'Douglas Fir-Larch No. 2'), ('hf_ss', 'Hem-Fir Select Structural'), ('hf_no1', 'Hem-Fir No. 1'), ('hf_no2', 'Hem-Fir No. 2'), ('lvl_1_55e', '1.55E LVL'), ('lvl_1_75e', '1.75E LVL'), ('lvl_1_9e', '1.9E LVL'), ('lvl_2_0e', '2.0E LVL'), ('lvl_2_1e', '2.1E LVL'), ('gl_20f_1_5e', '20F-1.5E Glulam'), ('gl_24f_1_8e', '24F-1.8E Glulam'), ('gl_26f_1_9e', '26F-1.9E Glulam'), ('gl_30f_2_1e', '30F-2.1E Glulam')], default='spf_no2', max_length=20),
        ),
        migrations.AlterField(
            model_name='beamdesign',
            name='nominal_size',
            field=models.CharField(choices=[('2x4', '2x4'), ('2x6', '2x6'), ('2x8', '2x8'), ('2x10', '2x10'), ('2x12', '2x12'), ('lvl_7.25', '7-1/4"'), ('lvl_9.25', '9-1/4"'), ('lvl_11.25', '11-1/4"'), ('lvl_11.875', '11-7/8"'), ('lvl_14', '14"'), ('lvl_16', '16"'), ('lvl_18', '18"'), ('gl_3.5x9', '3-1/2x9"'), ('gl_3.5x12', '3-1/2x12"'), ('gl_3.5x15', '3-1/2x15"'), ('gl_5.125x12', '5-1/8x12"'), ('gl_5.125x15', '5-1/8x15"'), ('gl_5.125x18', '5-1/8x18"'), ('gl_5.5x15', '5-1/2x15"'), ('gl_5.5x18', '5-1/2x18"'), ('gl_6.75x18', '6-3/4x18"'), ('gl_6.75x21', '6-3/4x21"')], max_length=20),
        ),
    ]
