# Generated by Django 6.0.3 on 2026-07-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0025_alter_beamdesign_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(choices=[('spf_ss', 'Spruce-Pine-Fir Select Structural'), ('spf_no1', 'Spruce-Pine-Fir No. 1'), ('spf_no2', 'Spruce-Pine-Fir No. 2'), ('dfl_ss', 'Douglas Fir-Larch Select Structural'), ('dfl_no1', 'Douglas Fir-Larch No. 1'), ('dfl_no2', 'Douglas Fir-Larch No. 2'), ('hf_ss', 'Hem-Fir Select Structural'), ('hf_no1', 'Hem-Fir No. 1'), ('hf_no2', 'Hem-Fir No. 2'), ('sp_ss', 'Southern Pine Select Structural'), ('sp_no1', 'Southern Pine No. 1'), ('sp_no2', 'Southern Pine No. 2'), ('lvl_1_55e', '1.55E LVL'), ('lvl_1_75e', '1.75E LVL'), ('lvl_1_9e', '1.9E LVL'), ('lvl_2_0e', '2.0E LVL'), ('lvl_2_1e', '2.1E LVL'), ('gl_20f_1_5e', '20F-1.5E Glulam'), ('gl_24f_1_8e', '24F-1.8E Glulam'), ('gl_26f_1_9e', '26F-1.9E Glulam'), ('gl_30f_2_1e', '30F-2.1E Glulam')], default='spf_no2', max_length=20)),
                ('nominal_size', models.CharField(choices=[('2x4', '2x4'), ('2x6', '2x6'), ('2x8', '2x8'), ('2x10', '2x10'), ('2x12', '2x12'), ('lvl_7.25', '7-1/4"'), ('lvl_9.25', '9-1/4"'), ('lvl_11.25', '11-1/4"'), ('lvl_11.875', '11-7/8"'), ('lvl_14', '14"'), ('lvl_16', '16"'), ('lvl_18', '18"'), ('gl_3.5x9', '3-1/2x9"'), ('gl_3.5x12', '3-1/2x12"'), ('gl_3.5x15', '3-1/2x15"'), ('gl_5.125x12', '5-1/8x12"'), ('gl_5.125x15', '5-1/8x15"'), ('gl_5.125x18', '5-1/8x18"'), ('gl_5.5x15', '5-1/2x15"'), ('gl_5.5x18', '5-1/2x18"'), ('gl_6.75x18', '6-3/4x18"'), ('gl_6.75x21', '6-3/4x21"')], max_length=20)),
                ('plies', models.PositiveSmallIntegerField(choices=[(1, '1 ply'), (2, '2 plies'), (3, '3 plies'), (4, '4 plies')], default=1)),
                ('dead_load_lb', models.FloatField(default=0)),
                ('live_load_lb', models.FloatField(default=0)),
                ('snow_load_lb', models.FloatField(default=0)),
                ('roof_live_load_lb', models.FloatField(default=0)),
                ('wind_load_lb', models.FloatField(default=0)),
                ('height_ft', models.FloatField()),
                ('unbraced_length_d_ft', models.FloatField(blank=True, null=True)),
                ('unbraced_length_b_ft', models.FloatField(blank=True, null=True)),
                ('end_condition', models.CharField(choices=[('1.0', 'Pinned - pinned, no sidesway (Ke = 1.0)'), ('0.8', 'Fixed - pinned, no sidesway (Ke = 0.8)'), ('0.65', 'Fixed - fixed, no sidesway (Ke = 0.65)'), ('2.1', 'Fixed - free / flagpole (Ke = 2.1)')], default='1.0', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_designs', to='beams.beamproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
