# Generated by Django 6.0.3 on 2026-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0027_alter_beamdesign_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columndesign',
            name='bending_unbraced_length_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='columndesign',
            name='lateral_load_plf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='columndesign',
            name='lateral_load_type',
            field=models.CharField(choices=[('dead', 'Dead'), ('live', 'Live'), ('snow', 'Snow'), ('roof_live', 'Roof live'), ('wind', 'Wind')], default='wind', max_length=12),
        ),
    ]
