# Generated by Django 6.0.3 on 2026-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0028_columndesign_bending_unbraced_length_ft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='end_notch_depth_in',
            field=models.FloatField(default=0),
        ),
    ]
