# Generated by Django 6.0.3 on 2026-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0029_beamdesign_end_notch_depth_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='hole_diameter_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beamdesign',
            name='hole_location_ft',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
