# Generated by Django 6.0.3 on 2026-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0030_beamdesign_hole_diameter_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamdesign',
            name='creep_factor',
            field=models.FloatField(choices=[(1.0, 'None - immediate deflection only'), (1.5, 'Seasoned / dry lumber (Kcr = 1.5)'), (2.0, 'Unseasoned or wet service (Kcr = 2.0)')], default=1.0),
        ),
    ]
