# Generated by Django 6.0.3 on 2026-07-22 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0031_beamdesign_creep_factor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('shear_planes', models.CharField(choices=[('single', 'Single shear (2 members)'), ('double', 'Double shear (3 members)')], default='single', max_length=8)),
                ('fastener_type', models.CharField(choices=[('bolt', 'Bolt'), ('lag', 'Lag screw'), ('nail', 'Common nail'), ('screw', 'Wood screw')], default='bolt', max_length=10)),
                ('diameter_in', models.FloatField()),
                ('fyb_psi', models.FloatField()),
                ('main_material', models.CharField(choices=[('spf_ss', 'Spruce-Pine-Fir Select Structural'), ('spf_no1', 'Spruce-Pine-Fir No. 1'), ('spf_no2', 'Spruce-Pine-Fir No. 2'), ('dfl_ss', 'Douglas Fir-Larch Select Structural'), ('dfl_no1', 'Douglas Fir-Larch No. 1'), ('dfl_no2', 'Douglas Fir-Larch No. 2'), ('hf_ss', 'Hem-Fir Select Structural'), ('hf_no1', 'Hem-Fir No. 1'), ('hf_no2', 'Hem-Fir No. 2'), ('sp_ss', 'Southern Pine Select Structural'), ('sp_no1', 'Southern Pine No. 1'), ('sp_no2', 'Southern Pine No. 2'), ('lvl_1_55e', '1.55E LVL'), ('lvl_1_75e', '1.75E LVL'), ('lvl_1_9e', '1.9E LVL'), ('lvl_2_0e', '2.0E LVL'), ('lvl_2_1e', '2.1E LVL'), ('pt_dfl_ss', 'Douglas Fir-Larch Select Structural (Posts & Timbers)'), ('pt_dfl_no1', 'Douglas Fir-Larch No. 1 (Posts & Timbers)'), ('pt_dfl_no2', 'Douglas Fir-Larch No. 2 (Posts & Timbers)'), ('gl_20f_1_5e', '20F-1.5E Glulam'), ('gl_24f_1_8e', '24F-1.8E Glulam'), ('gl_26f_1_9e', '26F-1.9E Glulam'), ('gl_30f_2_1e', '30F-2.1E Glulam')], default='spf_no2', max_length=20)),
                ('main_thickness_in', models.FloatField()),
                ('side_material', models.CharField(choices=[('spf_ss', 'Spruce-Pine-Fir Select Structural'), ('spf_no1', 'Spruce-Pine-Fir No. 1'), ('spf_no2', 'Spruce-Pine-Fir No. 2'), ('dfl_ss', 'Douglas Fir-Larch Select Structural'), ('dfl_no1', 'Douglas Fir-Larch No. 1'), ('dfl_no2', 'Douglas Fir-Larch No. 2'), ('hf_ss', 'Hem-Fir Select Structural'), ('hf_no1', 'Hem-Fir No. 1'), ('hf_no2', 'Hem-Fir No. 2'), ('sp_ss', 'Southern Pine Select Structural'), ('sp_no1', 'Southern Pine No. 1'), ('sp_no2', 'Southern Pine No. 2'), ('lvl_1_55e', '1.55E LVL'), ('lvl_1_75e', '1.75E LVL'), ('lvl_1_9e', '1.9E LVL'), ('lvl_2_0e', '2.0E LVL'), ('lvl_2_1e', '2.1E LVL'), ('pt_dfl_ss', 'Douglas Fir-Larch Select Structural (Posts & Timbers)'), ('pt_dfl_no1', 'Douglas Fir-Larch No. 1 (Posts & Timbers)'), ('pt_dfl_no2', 'Douglas Fir-Larch No. 2 (Posts & Timbers)'), ('gl_20f_1_5e', '20F-1.5E Glulam'), ('gl_24f_1_8e', '24F-1.8E Glulam'), ('gl_26f_1_9e', '26F-1.9E Glulam'), ('gl_30f_2_1e', '30F-2.1E Glulam')], default='spf_no2', max_length=20)),
                ('side_thickness_in', models.FloatField()),
                ('load_direction', models.CharField(choices=[('parallel', 'Parallel to grain'), ('perpendicular', 'Perpendicular to grain')], default='parallel', max_length=14)),
                ('load_duration', models.FloatField(choices=[(0.9, 'Dead / permanent (CD = 0.9)'), (1.0, 'Occupancy live (CD = 1.0)'), (1.15, 'Snow (CD = 1.15)'), (1.25, 'Construction (CD = 1.25)'), (1.6, 'Wind / seismic (CD = 1.6)')], default=1.0)),
                ('n_fasteners', models.PositiveIntegerField(default=1)),
                ('load_lb', models.FloatField(default=0)),
                ('fastener_spacing_in', models.FloatField(blank=True, null=True)),
                ('main_width_in', models.FloatField(blank=True, null=True)),
                ('side_width_in', models.FloatField(blank=True, null=True)),
                ('end_distance_in', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_designs', to='beams.beamproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
