# Generated by Django 6.0.3 on 2026-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0032_connectiondesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondesign',
            name='loading',
            field=models.CharField(choices=[('lateral', 'Lateral (shear)'), ('withdrawal', 'Withdrawal (axial)')], default='lateral', max_length=12),
        ),
    ]
