# Generated by Django 6.0.3 on 2026-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0033_connectiondesign_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondesign',
            name='service_condition',
            field=models.CharField(choices=[('dry', 'Dry (interior / protected)'), ('wet', 'Wet / exterior (MC > 19%)')], default='dry', max_length=10),
        ),
    ]
