# Generated by Django 6.0.3 on 2026-07-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0034_connectiondesign_service_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondesign',
            name='toe_nail',
            field=models.BooleanField(default=False),
        ),
    ]
