# Generated by Django 6.0.3 on 2026-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0035_connectiondesign_toe_nail'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondesign',
            name='temperature',
            field=models.CharField(choices=[('normal', 'Normal (T ≤ 100°F)'), ('warm', '100°F – 125°F'), ('hot', '125°F – 150°F')], default='normal', max_length=10),
        ),
    ]
