# Generated by Django 6.0.3 on 2026-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0036_connectiondesign_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondesign',
            name='edge_distance_in',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
