# Generated by Django 6.0.3 on 2026-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beams', '0037_connectiondesign_edge_distance_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondesign',
            name='side_type',
            field=models.CharField(choices=[('wood', 'Wood'), ('steel', 'Steel plate')], default='wood', max_length=8),
        ),
        migrations.AddField(
            model_name='connectiondesign',
            name='steel_grade',
            field=models.CharField(choices=[('a36', 'ASTM A36 (Fu 58 ksi, Fe 87,000)'), ('a572', 'ASTM A572 Gr.50 / A992 (Fu 65 ksi, Fe 97,500)')], default='a36', max_length=8),
        ),
    ]
